"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GO_OBO_FILE = os.path.join(BASE_DIR, 'data', 'go_ontology', 'go-basic.obo')
GENOME_DATA_DIR = os.path.join(BASE_DIR, 'data', 'genome')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f30m$ybpt=_^ghisaer)k&ct*p1@nhkpg2&kqv*hfhy(%!x&d2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# 允许的CSRF来源
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    #'http://172.28.226.114:8000',
    'http://172.28.226.114:3306',
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5713',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
    'http://127.0.0.1:5713',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'Browse.apps.BrowseConfig',
    'jbrowse.apps.JbrowseConfig',
    'tools.kegg_annotation',
    'tools.go_annotation',
    'tools.go_enrichment',
    'tools.kegg_enrichment',
    'tools.id_search.apps.IdSearchConfig',  
    'tools.blastp.apps.BlastpConfig',
    'tools.heatmap',
    'tools.gene_expression',
    'tools.gene_expression_in_eFP.apps.ThermalMapConfig',
    'debug_toolbar',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = [
    *(f'http://localhost:{port}' for port in range(5173, 5180)),
]
CORS_ALLOW_HEADERS = [
    'x-request-id',
    'content-type',
    'x-csrftoken',
    'authorization',
    'accept',
    'origin',
]
ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            #os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, '../vue_app', 'dist'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "CottonOGD-ortho",
        "USER": "root",
        "PASSWORD": "1234",
        "HOST": "localhost",
        #"HOST": "172.28.226.114",
        "PORT": "3306",
         'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            }
    }
}
"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# 增加静态文件处理的缓冲区大小，以支持大文件加载
DJANGO_SERVE_STATIC_FILES_WITH_BUFFER_SIZE = 1024 * 1024 * 1024  # 1GB缓冲区

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
X_FRAME_OPTIONS = 'SAMEORIGIN'

STATIC_URL = '/assets/'
# 确保static/jbrowse目录被正确映射到/assets/jbrowse/URL
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # 主static目录，包含jbrowse
    os.path.join(BASE_DIR, '../vue_app/dist'),  # Vue应用构建输出目录
    os.path.join(BASE_DIR, '../vue_app/dist/assets'),  # Vue应用资源目录
]

#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
