# Generated by Django 5.2.3 on 2025-12-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gene_annotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Gene_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('GO_annotation', models.TextField(blank=True, null=True)),
                ('KEGG_annotation', models.TextField(blank=True, null=True)),
                ('KOG_class', models.TextField(blank=True, null=True)),
                ('KOG_class_annotation', models.TextField(blank=True, null=True)),
                ('Pfam_annotation', models.TextField(blank=True, null=True)),
                ('Swissprot_annotation', models.TextField(blank=True, null=True)),
                ('TrEMBL_annotation', models.TextField(blank=True, null=True)),
                ('nr_annotation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gene_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('IDs', models.TextField(blank=True, null=True)),
                ('seqid', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(max_length=10)),
                ('attributes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gene_info',
            },
        ),
        migrations.CreateModel(
            name='gene_seq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mrna_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mrna_seq', models.TextField(blank=True, null=True)),
                ('cds_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cds_seq', models.TextField(blank=True, null=True)),
                ('protein_id', models.CharField(blank=True, max_length=100, null=True)),
                ('protein_seq', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genome_Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('fasta_file', models.FileField(upload_to='data/genomes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='genome_seq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(blank=True, max_length=100, null=True)),
                ('seq', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
