# Generated by Django 5.2.3 on 2025-12-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene_seq',
            name='cds_id',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='protein_id',
        ),
        migrations.AddField(
            model_name='gene_seq',
            name='downstream_seq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gene_seq',
            name='upstream_seq',
            field=models.TextField(blank=True, null=True),
        ),
    ]
