# Generated by Django 5.2.3 on 2025-11-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gene_info",
            name="IDs",
            field=models.TextField(blank=True, null=True),
        ),
    ]
