# Generated by Django 5.2.3 on 2025-12-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_search', '0002_remove_gene_seq_cds_id_remove_gene_seq_protein_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene_seq',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genome_seq',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
