# Generated by Django 5.2.3 on 2025-11-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0002_gene_info_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene_info",
            name="Gene_ID",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
