# Generated by Django 5.2.3 on 2025-11-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0003_alter_gene_info_gene_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene_info",
            name="Name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
