# Generated by Django 5.2.3 on 2025-12-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_search', '0003_alter_gene_seq_id_alter_genome_seq_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gene_annotation',
            index=models.Index(fields=['Gene_ID'], name='gene_annotation_gene_id_idx'),
        ),
        migrations.AddIndex(
            model_name='gene_info',
            index=models.Index(fields=['IDs'], name='gene_info_ids_idx'),
        ),
        migrations.AddIndex(
            model_name='gene_info',
            index=models.Index(fields=['seqid', 'start', 'end'], name='gene_info_location_idx'),
        ),
        migrations.AddIndex(
            model_name='gene_seq',
            index=models.Index(fields=['gene_id'], name='gene_seq_gene_id_idx'),
        ),
        migrations.AddIndex(
            model_name='gene_seq',
            index=models.Index(fields=['mrna_id'], name='gene_seq_mrna_id_idx'),
        ),
        migrations.AddIndex(
            model_name='genome_seq',
            index=models.Index(fields=['gene_id'], name='genome_seq_gene_id_idx'),
        ),
    ]
