# Generated by Django 5.2.3 on 2025-11-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0004_alter_gene_info_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene_info",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
