# Generated by Django 5.2.3 on 2025-11-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0005_alter_gene_info_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gene_info",
            name="attributes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
