# Generated by Django 5.2.3 on 2025-12-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_search', '0005_alter_gene_info_ids'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gene_annotation',
            name='gene_annotation_gene_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='gene_info',
            name='gene_info_ids_idx',
        ),
        migrations.RemoveIndex(
            model_name='gene_info',
            name='gene_info_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='gene_seq',
            name='gene_seq_gene_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='gene_seq',
            name='gene_seq_mrna_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='genome_seq',
            name='genome_seq_gene_id_idx',
        ),
        migrations.AddField(
            model_name='gene_seq',
            name='cdna_seq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gene_info',
            name='IDs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gene_seq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genome_seq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
