# Generated by Django 5.2.3 on 2025-12-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_search', '0006_remove_gene_annotation_gene_annotation_gene_id_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene_info',
            name='IDs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
