# Generated by Django 5.2.3 on 2025-11-12 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0006_gene_info_attributes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gene_info",
            name="Name",
        ),
    ]
