# Generated by Django 5.2.3 on 2025-11-12 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Species", "0005_alter_species_lai_value"),
        ("id_search", "0007_remove_gene_info_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seqid", models.CharField(max_length=100)),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
                ("type", models.CharField(max_length=100)),
                ("strand", models.CharField(max_length=1)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CDS_seq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.TextField()),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="id_search.gene"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genome_Assembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fasta_file", models.FileField(upload_to="genomes/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species",
                        to="Species.species",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gene",
            name="assembly",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="id_search.genome_assembly",
            ),
        ),
        migrations.CreateModel(
            name="mRNA_seq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.TextField()),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="id_search.gene"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="protein_seq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.TextField()),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="id_search.gene"
                    ),
                ),
            ],
        ),
    ]
