# Generated by Django 5.2.3 on 2025-11-12 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "id_search",
            "0008_gene_cds_seq_genome_assembly_gene_assembly_mrna_seq_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mrna_seq",
            name="gene",
        ),
        migrations.RemoveField(
            model_name="protein_seq",
            name="gene",
        ),
        migrations.AddField(
            model_name="gene",
            name="gene_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genes",
                to="id_search.gene_info",
            ),
        ),
        migrations.CreateModel(
            name="gene_seq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mrna_id", models.CharField(blank=True, max_length=100, null=True)),
                ("mrna_seq", models.TextField(blank=True, null=True)),
                ("cds_id", models.CharField(blank=True, max_length=100, null=True)),
                ("cds_seq", models.TextField(blank=True, null=True)),
                ("protein_id", models.CharField(blank=True, max_length=100, null=True)),
                ("protein_seq", models.TextField(blank=True, null=True)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="id_search.gene"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CDS_seq",
        ),
        migrations.DeleteModel(
            name="mRNA_seq",
        ),
        migrations.DeleteModel(
            name="protein_seq",
        ),
    ]
