# Generated by Django 5.2.3 on 2025-11-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0009_remove_mrna_seq_gene_remove_protein_seq_gene_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene",
            name="gene_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="id_search.gene_info",
            ),
        ),
    ]
