# Generated by Django 5.2.3 on 2025-11-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0010_alter_gene_gene_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gene",
            old_name="gene_id",
            new_name="gene",
        ),
    ]
