# Generated by Django 5.2.3 on 2025-11-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0011_rename_gene_id_gene_gene"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genome_assembly",
            name="fasta_file",
            field=models.FileField(upload_to="data/genomes/"),
        ),
    ]
