# Generated by Django 5.2.3 on 2025-11-12 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0012_alter_genome_assembly_fasta_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene_seq",
            name="gene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="id_search.gene_info"
            ),
        ),
    ]
