# Generated by Django 5.2.3 on 2025-11-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0013_alter_gene_seq_gene"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene_seq",
            name="gene",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
