# Generated by Django 5.2.3 on 2025-11-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0014_alter_gene_seq_gene"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gene_seq",
            old_name="gene",
            new_name="gene_id",
        ),
    ]
