# Generated by Django 5.2.3 on 2025-11-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0015_rename_gene_gene_seq_gene_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Orthogroups",
        ),
    ]
