# Generated by Django 5.2.3 on 2025-11-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0016_delete_orthogroups"),
    ]

    operations = [
        migrations.AddField(
            model_name="gene_info",
            name="GO_annotation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gene_info",
            name="KEGG_annotation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gene_info",
            name="KOG_class",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gene_info",
            name="KOG_class_annotation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
