# Generated by Django 5.2.3 on 2025-11-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "id_search",
            "0017_gene_info_go_annotation_gene_info_kegg_annotation_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="gene_annotation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("Gene_ID", models.CharField(blank=True, max_length=100, null=True)),
                ("GO_annotation", models.TextField(blank=True, null=True)),
                ("KEGG_annotation", models.TextField(blank=True, null=True)),
                ("KOG_class", models.CharField(blank=True, max_length=100, null=True)),
                ("KOG_class_annotation", models.TextField(blank=True, null=True)),
                ("Pfam_annotation", models.TextField(blank=True, null=True)),
                ("Swissprot_annotation", models.TextField(blank=True, null=True)),
                ("TrEMBL_annotation", models.TextField(blank=True, null=True)),
                ("nr_annotation", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="gene_info",
            name="GO_annotation",
        ),
        migrations.RemoveField(
            model_name="gene_info",
            name="KEGG_annotation",
        ),
        migrations.RemoveField(
            model_name="gene_info",
            name="KOG_class",
        ),
        migrations.RemoveField(
            model_name="gene_info",
            name="KOG_class_annotation",
        ),
        migrations.RemoveField(
            model_name="gene_info",
            name="Pfam_annotation",
        ),
        migrations.RemoveField(
            model_name="gene_info",
            name="Swissprot_annotation",
        ),
        migrations.RemoveField(
            model_name="gene_info",
            name="TrEMBL_annotation",
        ),
        migrations.RemoveField(
            model_name="gene_info",
            name="nr_annotation",
        ),
        migrations.AddField(
            model_name="gene_info",
            name="species",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Gene",
        ),
    ]
