# Generated by Django 5.2.3 on 2025-11-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0018_gene_annotation_remove_gene_info_go_annotation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gene_info",
            name="Gene_ID",
        ),
    ]
