# Generated by Django 5.2.3 on 2025-11-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_search", "0019_remove_gene_info_gene_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene_annotation",
            name="KOG_class",
            field=models.TextField(blank=True, null=True),
        ),
    ]
