# Generated by Django 5.2.3 on 2025-12-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_search', '0020_alter_gene_annotation_kog_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='genome_seq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=100)),
                ('seq', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='cds_id',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='protein_id',
        ),
        migrations.AddField(
            model_name='gene_seq',
            name='cdna_seq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gene_seq',
            name='down_seq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gene_seq',
            name='ups_seq',
            field=models.TextField(blank=True, null=True),
        ),
    ]
