# Generated by Django 5.2.3 on 2025-12-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_search', '0021_genome_seq_remove_gene_seq_cds_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='genome_seq',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='cdna_seq',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='down_seq',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='ups_seq',
        ),
        migrations.AddField(
            model_name='gene_seq',
            name='cds_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gene_seq',
            name='protein_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
