# Generated by Django 5.2.3 on 2025-12-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_search', '0022_delete_genome_seq_remove_gene_seq_cdna_seq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='genome_seq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(blank=True, max_length=100, null=True)),
                ('seq', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
