# Generated by Django 5.2.7 on 2025-11-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cotton_Species', models.CharField(max_length=100)),
                ('Genome_type', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Accession', models.CharField(max_length=100)),
                ('Ploidy', models.CharField(max_length=100)),
                ('Assembling_institution', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('Article', models.CharField(max_length=100)),
                ('LAI_value', models.CharField(max_length=100)),
                ('Busco', models.CharField(max_length=100)),
                ('Genome_size', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Species.species')),
            ],
        ),
    ]
