# Generated by Django 5.2.3 on 2025-11-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Species", "0002_alter_species_options_alter_species_accession_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="species",
            options={},
        ),
        migrations.AlterField(
            model_name="species",
            name="Cotton_Species",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="棉花物种"
            ),
        ),
    ]
