# Generated by Django 5.2.3 on 2025-11-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Species", "0003_alter_species_options_alter_species_cotton_species"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="Busco",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="BUSCO值"
            ),
        ),
    ]
