# Generated by Django 5.2.3 on 2025-12-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FPKM4',
            fields=[
                ('gene_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Root', models.FloatField(blank=True, max_length=100, null=True)),
                ('Stem', models.FloatField(blank=True, max_length=100, null=True)),
                ('Cotyledon', models.FloatField(blank=True, max_length=100, null=True)),
                ('Leaf', models.FloatField(blank=True, max_length=100, null=True)),
                ('Pholem', models.FloatField(blank=True, max_length=100, null=True)),
                ('Sepal', models.FloatField(blank=True, max_length=100, null=True)),
                ('Bract', models.FloatField(blank=True, max_length=100, null=True)),
                ('Petal', models.FloatField(blank=True, max_length=100, null=True)),
                ('Anther', models.FloatField(blank=True, max_length=100, null=True)),
                ('Stigma', models.FloatField(blank=True, max_length=100, null=True)),
                ('number_0_DPA_ovules', models.FloatField(blank=True, db_column='0_DPA_ovules', max_length=100, null=True)),
                ('number_3_DPA_fibers', models.FloatField(blank=True, db_column='3_dpa_fibers', max_length=100, null=True)),
                ('number_6_DPA_fibers', models.FloatField(blank=True, db_column='6_dpa_fibers', max_length=100, null=True)),
                ('number_9_DPA_fibers', models.FloatField(blank=True, db_column='9_dpa_fibers', max_length=100, null=True)),
                ('number_12_DPA_fibers', models.FloatField(blank=True, db_column='12_dpa_fibers', max_length=100, null=True)),
                ('number_15_DPA_fibers', models.FloatField(blank=True, db_column='15_dpa_fibers', max_length=100, null=True)),
                ('number_18_DPA_fibers', models.FloatField(blank=True, db_column='18_dpa_fibers', max_length=100, null=True)),
                ('number_21_DPA_fibers', models.FloatField(blank=True, db_column='21_dpa_fibers', max_length=100, null=True)),
                ('number_24_DPA_fibers', models.FloatField(blank=True, db_column='24_dpa_fibers', max_length=100, null=True)),
                ('dpa0', models.FloatField(blank=True, max_length=100, null=True)),
                ('number_5_DPA_ovules', models.FloatField(blank=True, db_column='5_dpa_ovules', max_length=100, null=True)),
                ('number_10_DPA_ovules', models.FloatField(blank=True, db_column='10_dpa_ovules', max_length=100, null=True)),
                ('number_20_DPA_ovules', models.FloatField(blank=True, db_column='20_dpa_ovules', max_length=100, null=True)),
                ('Seed', models.FloatField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'fpkm4',
                'managed': True,
            },
        ),
    ]
