# Generated by Django 5.2.3 on 2026-01-11 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geneid', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'genemaster',
            },
        ),
        migrations.CreateModel(
            name='blastdb_path',
            fields=[
                ('db_type', models.CharField(blank=True, max_length=100, null=True)),
                ('db_name', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'blastdb',
                'indexes': [models.Index(fields=['db_name'], name='blastdb_db_name_22729b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Species_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='名称')),
                ('Cotton_Species', models.CharField(blank=True, max_length=255, null=True, verbose_name='棉花物种')),
                ('Genome_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='基因组类型')),
                ('Category', models.CharField(blank=True, max_length=100, null=True, verbose_name='类别')),
                ('Accession', models.CharField(blank=True, max_length=100, null=True, verbose_name='登录号')),
                ('Ploidy', models.CharField(blank=True, max_length=50, null=True, verbose_name='倍性')),
                ('Assembling_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='组装机构')),
                ('Website', models.TextField(blank=True, null=True, verbose_name='网站')),
                ('Article', models.CharField(blank=True, max_length=255, null=True, verbose_name='文章')),
                ('LAI_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='LAI值')),
                ('Busco', models.CharField(blank=True, max_length=100, null=True, verbose_name='BUSCO值')),
                ('Genome_size', models.BigIntegerField(blank=True, null=True, verbose_name='基因组大小')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('alias', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='实际显示名')),
            ],
            options={
                'db_table': 'species',
                'indexes': [models.Index(fields=['alias'], name='species_alias_c4cf64_idx'), models.Index(fields=['name'], name='species_name_abd81c_idx')],
            },
        ),
        migrations.CreateModel(
            name='genome_seq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.TextField(blank=True, null=True)),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
        ),
        migrations.AddField(
            model_name='genemaster',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name'),
        ),
        migrations.CreateModel(
            name='gene_seq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mrna_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mrna_seq', models.TextField(blank=True, null=True)),
                ('cds_seq', models.TextField(blank=True, null=True)),
                ('cdna_seq', models.TextField(blank=True, null=True)),
                ('upstream_seq', models.TextField(blank=True, null=True)),
                ('downstream_seq', models.TextField(blank=True, null=True)),
                ('protein_seq', models.TextField(blank=True, null=True)),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='gene_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seqid', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(max_length=10)),
                ('attributes', models.TextField(blank=True, null=True)),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
            options={
                'db_table': 'gene_assembly',
            },
        ),
        migrations.CreateModel(
            name='gene_expression',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tissue', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50, null=True)),
                ('value', models.FloatField()),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
            options={
                'db_table': 'expression',
            },
        ),
        migrations.CreateModel(
            name='gene_annotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Gene_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('GO_annotation', models.TextField(blank=True, null=True)),
                ('KEGG_annotation', models.TextField(blank=True, null=True)),
                ('KOG_class', models.TextField(blank=True, null=True)),
                ('KOG_class_annotation', models.TextField(blank=True, null=True)),
                ('Pfam_annotation', models.TextField(blank=True, null=True)),
                ('Swissprot_annotation', models.TextField(blank=True, null=True)),
                ('TrEMBL_annotation', models.TextField(blank=True, null=True)),
                ('nr_annotation', models.TextField(blank=True, null=True)),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('TF_class', models.CharField(db_column='TF_class', max_length=100)),
                ('TF_name', models.CharField(db_column='TF_name', max_length=100)),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
            options={
                'db_table': 'genefamily',
            },
        ),
        migrations.AddIndex(
            model_name='genemaster',
            index=models.Index(fields=['geneid'], name='genemaster_geneid_d23a37_idx'),
        ),
        migrations.AddIndex(
            model_name='genemaster',
            index=models.Index(fields=['genome'], name='genemaster_genome__321e68_idx'),
        ),
        migrations.AddConstraint(
            model_name='genemaster',
            constraint=models.UniqueConstraint(fields=('genome', 'geneid'), name='genome_gene'),
        ),
        migrations.AddIndex(
            model_name='gene_expression',
            index=models.Index(fields=['geneid', 'genome'], name='expression_geneid__348597_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['geneid', 'genome'], name='genefamily_geneid__ad6c24_idx'),
        ),
    ]
