# Generated by Django 5.2.3 on 2026-01-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene_expression',
            name='geneid',
        ),
        migrations.RemoveField(
            model_name='gene_expression',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='gene_info',
            name='geneid',
        ),
        migrations.RemoveField(
            model_name='gene_info',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='geneid',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='genome_seq',
            name='geneid',
        ),
        migrations.RemoveField(
            model_name='genome_seq',
            name='genome',
        ),
        migrations.DeleteModel(
            name='gene_annotation',
        ),
        migrations.DeleteModel(
            name='gene_expression',
        ),
        migrations.DeleteModel(
            name='gene_info',
        ),
        migrations.DeleteModel(
            name='gene_seq',
        ),
        migrations.DeleteModel(
            name='genome_seq',
        ),
    ]
