# Generated by Django 5.2.3 on 2026-01-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0002_remove_gene_expression_geneid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='geneid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster', to_field='geneid', unique=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genemaster',
            name='geneid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
