# Generated by Django 5.2.3 on 2026-01-11 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0003_alter_family_geneid_alter_family_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gene_annotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Gene_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('GO_annotation', models.TextField(blank=True, null=True)),
                ('KEGG_annotation', models.TextField(blank=True, null=True)),
                ('KOG_class', models.TextField(blank=True, null=True)),
                ('KOG_class_annotation', models.TextField(blank=True, null=True)),
                ('Pfam_annotation', models.TextField(blank=True, null=True)),
                ('Swissprot_annotation', models.TextField(blank=True, null=True)),
                ('TrEMBL_annotation', models.TextField(blank=True, null=True)),
                ('nr_annotation', models.TextField(blank=True, null=True)),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='gene_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seqid', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(max_length=10)),
                ('attributes', models.TextField(blank=True, null=True)),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
            options={
                'db_table': 'gene_assembly',
            },
        ),
        migrations.CreateModel(
            name='gene_seq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mrna_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mrna_seq', models.TextField(blank=True, null=True)),
                ('cds_seq', models.TextField(blank=True, null=True)),
                ('cdna_seq', models.TextField(blank=True, null=True)),
                ('upstream_seq', models.TextField(blank=True, null=True)),
                ('downstream_seq', models.TextField(blank=True, null=True)),
                ('protein_seq', models.TextField(blank=True, null=True)),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='genome_seq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.TextField(blank=True, null=True)),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='gene_expression',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tissue', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50, null=True)),
                ('value', models.FloatField()),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
            options={
                'db_table': 'expression',
                'indexes': [models.Index(fields=['geneid', 'genome'], name='expression_geneid__348597_idx')],
            },
        ),
    ]
