# Generated by Django 5.2.3 on 2026-01-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0004_gene_annotation_gene_info_gene_seq_genome_seq_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gene_seq',
            table='gene_seq',
        ),
        migrations.AlterModelTable(
            name='genome_seq',
            table='genome_seq',
        ),
    ]
