# Generated by Django 5.2.3 on 2026-01-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0005_alter_gene_seq_table_alter_genome_seq_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gene_annotation',
            table='gene_annotation',
        ),
    ]
