# Generated by Django 5.2.3 on 2026-01-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0006_alter_gene_annotation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene_info',
            name='phase',
            field=models.CharField(default='.', max_length=10),
            preserve_default=False,
        ),
    ]
