# Generated by Django 5.2.3 on 2026-01-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0007_gene_info_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene_info',
            name='value',
            field=models.CharField(default='.', max_length=10),
            preserve_default=False,
        ),
    ]
