# Generated by Django 5.2.3 on 2026-01-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0008_gene_info_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene_annotation',
            name='geneid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster', to_field='geneid'),
        ),
        migrations.AlterField(
            model_name='gene_expression',
            name='geneid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster', to_field='geneid'),
        ),
        migrations.AlterField(
            model_name='gene_info',
            name='geneid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster', to_field='geneid'),
        ),
        migrations.AlterField(
            model_name='gene_seq',
            name='geneid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster', to_field='geneid'),
        ),
        migrations.AlterField(
            model_name='genome_seq',
            name='geneid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster', to_field='geneid'),
        ),
    ]
