# Generated by Django 5.2.3 on 2026-01-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0009_alter_gene_annotation_geneid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genemaster',
            name='alias',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='检索名'),
        ),
    ]
