# Generated by Django 5.2.3 on 2026-01-13 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0010_genemaster_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene_annotation',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='annotation', serialize=False, to='CottonOGD.genemaster'),
        ),
    ]
