# Generated by Django 5.2.3 on 2026-01-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0011_alter_gene_annotation_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='family',
            new_name='genefamily_geneid_2f60ee_idx',
            old_name='genefamily_geneid__ad6c24_idx',
        ),
        migrations.AlterField(
            model_name='family',
            name='geneid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CottonOGD.genemaster'),
        ),
    ]
