# Generated by Django 5.2.3 on 2026-01-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0012_rename_genefamily_geneid__ad6c24_idx_genefamily_geneid_2f60ee_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene_annotation',
            old_name='Gene_ID',
            new_name='annoation_source',
        ),
        migrations.RenameField(
            model_name='gene_annotation',
            old_name='GO_annotation',
            new_name='annotation',
        ),
        migrations.RemoveField(
            model_name='gene_annotation',
            name='KEGG_annotation',
        ),
        migrations.RemoveField(
            model_name='gene_annotation',
            name='KOG_class',
        ),
        migrations.RemoveField(
            model_name='gene_annotation',
            name='KOG_class_annotation',
        ),
        migrations.RemoveField(
            model_name='gene_annotation',
            name='Pfam_annotation',
        ),
        migrations.RemoveField(
            model_name='gene_annotation',
            name='Swissprot_annotation',
        ),
        migrations.RemoveField(
            model_name='gene_annotation',
            name='TrEMBL_annotation',
        ),
        migrations.RemoveField(
            model_name='gene_annotation',
            name='nr_annotation',
        ),
    ]
