# Generated by Django 5.2.3 on 2026-01-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0013_rename_gene_id_gene_annotation_annoation_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene_info',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='assembly', serialize=False, to='CottonOGD.genemaster'),
        ),
    ]
