# Generated by Django 5.2.3 on 2026-01-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0014_alter_gene_info_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene_info',
            name='species',
        ),
    ]
