# Generated by Django 5.2.3 on 2026-01-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0015_remove_gene_info_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene_info',
            name='geneid',
        ),
        migrations.RemoveField(
            model_name='gene_info',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='gene_info',
            name='id',
        ),
        migrations.DeleteModel(
            name='gene_annotation',
        ),
        migrations.DeleteModel(
            name='gene_info',
        ),
    ]
