# Generated by Django 5.2.3 on 2026-01-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0016_remove_gene_info_geneid_remove_gene_info_genome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gene_annotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_id', models.IntegerField(default='0')),
                ('annoation_source', models.CharField(blank=True, max_length=100, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster', to_field='geneid')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
            options={
                'db_table': 'gene_annotation',
            },
        ),
        migrations.CreateModel(
            name='gene_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_id', models.IntegerField(default='0')),
                ('seqid', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(max_length=10)),
                ('phase', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=10)),
                ('attributes', models.TextField(blank=True, null=True)),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.genemaster', to_field='geneid')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
            options={
                'db_table': 'gene_assembly',
            },
        ),
    ]
