# Generated by Django 5.2.3 on 2026-01-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0017_gene_annotation_gene_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene_seq',
            old_name='cdna_seq',
            new_name='sequence',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='cds_seq',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='downstream_seq',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='mrna_seq',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='protein_seq',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='upstream_seq',
        ),
        migrations.AddField(
            model_name='gene_seq',
            name='gene_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gene_seq',
            name='id_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='genome_seq',
        ),
    ]
