# Generated by Django 5.2.3 on 2026-01-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0018_rename_cdna_seq_gene_seq_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene_expression',
            name='id_id',
            field=models.IntegerField(default='0'),
        ),
    ]
