# Generated by Django 5.2.3 on 2026-01-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0019_gene_expression_id_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blastdb_path',
        ),
    ]
