# Generated by Django 5.2.3 on 2026-01-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0020_delete_blastdb_path'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gene_annotation',
            index=models.Index(fields=['id_id'], name='gene_annota_id_id_e544b3_idx'),
        ),
        migrations.AddIndex(
            model_name='gene_seq',
            index=models.Index(fields=['id_id'], name='gene_seq_id_id_cec9fa_idx'),
        ),
    ]
