# Generated by Django 5.2.3 on 2026-01-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0021_gene_annotation_gene_annota_id_id_e544b3_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gene_expression',
            index=models.Index(fields=['id_id'], name='expression_id_id_55bece_idx'),
        ),
        migrations.AddIndex(
            model_name='gene_info',
            index=models.Index(fields=['id_id'], name='gene_assemb_id_id_d0e888_idx'),
        ),
    ]
