# Generated by Django 5.2.3 on 2026-02-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0022_gene_expression_expression_id_id_55bece_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gene_expression',
            new_name='expression_geneid_8744a2_idx',
            old_name='expression_geneid__348597_idx',
        ),
        migrations.AlterField(
            model_name='gene_expression',
            name='geneid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
