# Generated by Django 5.2.3 on 2026-03-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0023_rename_expression_geneid__348597_idx_expression_geneid_8744a2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene_annotation',
            name='geneid',
        ),
        migrations.RemoveField(
            model_name='gene_info',
            name='geneid',
        ),
        migrations.RemoveField(
            model_name='gene_seq',
            name='geneid',
        ),
        migrations.AddField(
            model_name='gene_annotation',
            name='geneid_id',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='gene_info',
            name='geneid_id',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='gene_seq',
            name='geneid_id',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='genemaster',
            name='geneid',
            field=models.CharField(max_length=200),
        ),
    ]
