# Generated by Django 5.2.3 on 2026-03-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0024_remove_gene_annotation_geneid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genemaster',
            name='alias',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='检索名'),
        ),
    ]
