# Generated by Django 5.2.3 on 2026-03-10 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0025_alter_genemaster_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='gene_go',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_id', models.IntegerField(default='0')),
                ('geneid_id', models.CharField(default='0', max_length=200)),
                ('go_id', models.CharField(blank=True, max_length=100, null=True)),
                ('go_description', models.CharField(blank=True, max_length=100, null=True)),
                ('go_type', models.CharField(blank=True, max_length=100, null=True)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
            options={
                'db_table': 'gene_go',
                'indexes': [models.Index(fields=['id_id'], name='gene_go_id_id_7aa961_idx')],
            },
        ),
        migrations.CreateModel(
            name='gene_kegg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_id', models.IntegerField(default='0')),
                ('geneid_id', models.CharField(default='0', max_length=200)),
                ('kegg_id', models.CharField(blank=True, max_length=100, null=True)),
                ('kegg_description', models.CharField(blank=True, max_length=100, null=True)),
                ('kegg_type', models.CharField(blank=True, max_length=100, null=True)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CottonOGD.species_info', to_field='name')),
            ],
            options={
                'db_table': 'gene_kegg',
                'indexes': [models.Index(fields=['id_id'], name='gene_kegg_id_id_c320d8_idx')],
            },
        ),
    ]
