# Generated by Django 5.2.3 on 2026-03-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0026_gene_go_gene_kegg'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene_annotation',
            name='annoation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
