# Generated by Django 5.2.3 on 2026-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0027_gene_annotation_annoation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene_annotation',
            name='geneid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gene_go',
            name='geneid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gene_kegg',
            name='geneid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
