# Generated by Django 5.2.3 on 2026-03-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0028_gene_annotation_geneid_gene_go_geneid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeTissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tissue', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genome', models.ForeignKey(db_column='genome', on_delete=django.db.models.deletion.DO_NOTHING, to='CottonOGD.species_info', to_field='name')),
            ],
            options={
                'db_table': 'genome_tissue',
                'managed': True,
                'indexes': [models.Index(fields=['genome'], name='gt_genome_idx')],
                'unique_together': {('genome', 'tissue')},
            },
        ),
    ]
