# Generated by Django 5.2.3 on 2026-05-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonOGD', '0029_genometissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('seq_hash', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='序列MD5')),
                ('method', models.CharField(db_index=True, max_length=20, verbose_name='比对方法')),
                ('result_json', models.JSONField(verbose_name='结果JSON数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '搜索缓存',
                'db_table': 'search_cache',
            },
        ),
    ]
