# Generated by Django 5.2.3 on 2026-05-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CottonOGD", "0030_searchcache"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="gene_info",
            index=models.Index(fields=["seqid"], name="gene_assemb_seqid_6c370a_idx"),
        ),
        migrations.AddIndex(
            model_name="gene_info",
            index=models.Index(fields=["start"], name="gene_assemb_start_0587da_idx"),
        ),
        migrations.AddIndex(
            model_name="gene_info",
            index=models.Index(fields=["end"], name="gene_assemb_end_7c9435_idx"),
        ),
    ]
