# Generated by Django 5.2.3 on 2026-05-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CottonOGD", "0031_gene_info_gene_assemb_seqid_6c370a_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genome_Synteny",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("Ref_genome", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Ref_genome_chr",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Ref_genome_start", models.IntegerField()),
                ("Ref_genome_end", models.IntegerField()),
                (
                    "Query_genome",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Query_genome_chr",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Query_genome_start", models.IntegerField()),
                ("Query_genome_end", models.IntegerField()),
                (
                    "Variation_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "genome_synteny",
                "indexes": [
                    models.Index(fields=["id"], name="genome_synt_id_0552c0_idx")
                ],
            },
        ),
    ]
