# Generated by Django 5.2.3 on 2026-05-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CottonOGD", "0032_genome_synteny"),
    ]

    operations = [
        migrations.AddField(
            model_name="genome_synteny",
            name="Alt_seq",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genome_synteny",
            name="Parent_Variation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="genome_synteny",
            name="Ref_seq",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genome_synteny",
            name="copygain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="genome_synteny",
            name="son_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="genome_synteny",
            name="Query_genome",
            field=models.IntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="genome_synteny",
            name="Query_genome_start",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="genome_synteny",
            name="Ref_genome",
            field=models.IntegerField(default="0"),
        ),
    ]
