# Generated by Django 5.2.3 on 2026-05-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CottonOGD", "0033_genome_synteny_alt_seq_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gene_go",
            name="geneid",
        ),
        migrations.RemoveField(
            model_name="gene_go",
            name="geneid_id",
        ),
        migrations.RemoveField(
            model_name="gene_go",
            name="genome",
        ),
        migrations.RemoveField(
            model_name="gene_go",
            name="go_description",
        ),
        migrations.RemoveField(
            model_name="gene_go",
            name="go_type",
        ),
        migrations.RemoveField(
            model_name="gene_kegg",
            name="geneid",
        ),
        migrations.RemoveField(
            model_name="gene_kegg",
            name="geneid_id",
        ),
        migrations.RemoveField(
            model_name="gene_kegg",
            name="genome",
        ),
        migrations.RemoveField(
            model_name="gene_kegg",
            name="kegg_description",
        ),
        migrations.RemoveField(
            model_name="gene_kegg",
            name="kegg_type",
        ),
        migrations.AlterField(
            model_name="genome_synteny",
            name="Query_genome_start",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
