# Generated by Django 5.2.3 on 2026-05-16 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CottonOGD", "0034_remove_gene_go_geneid_remove_gene_go_geneid_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoTerm",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("definition", models.TextField()),
                (
                    "namespace",
                    models.CharField(
                        choices=[
                            ("biological_process", "Biological Process"),
                            ("molecular_function", "Molecular Function"),
                            ("cellular_component", "Cellular Component"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_obsolete", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GO Term",
                "verbose_name_plural": "GO Terms",
                "db_table": "go_term",
            },
        ),
        migrations.CreateModel(
            name="GoRelationship",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("is_a", "is_a"),
                            ("part_of", "part_of"),
                            ("regulates", "regulates"),
                            ("negatively_regulates", "negatively_regulates"),
                            ("positively_regulates", "positively_regulates"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_inferred", models.BooleanField(default=False)),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_relationships",
                        to="CottonOGD.goterm",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_relationships",
                        to="CottonOGD.goterm",
                    ),
                ),
            ],
            options={
                "verbose_name": "GO Relationship",
                "verbose_name_plural": "GO Relationships",
                "db_table": "go_relationship",
                "unique_together": {("subject", "object", "relationship_type")},
            },
        ),
    ]
