# Generated by Django 5.2.3 on 2026-05-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CottonOGD", "0035_goterm_gorelationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gorelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("is_a", "is_a"),
                    ("part_of", "part_of"),
                    ("regulates", "regulates"),
                    ("negatively_regulates", "negatively_regulates"),
                    ("positively_regulates", "positively_regulates"),
                    ("replaced_by", "replaced_by"),
                    ("consider", "consider"),
                ],
                max_length=50,
            ),
        ),
    ]
