# Generated by Django 5.2.3 on 2026-05-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CottonOGD", "0036_alter_gorelationship_relationship_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ECNumber",
            fields=[
                (
                    "ec_number",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="EC编号",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="EC名称")),
            ],
            options={
                "verbose_name": "EC编号",
                "verbose_name_plural": "EC编号",
                "db_table": "ec_number",
            },
        ),
        migrations.CreateModel(
            name="KOTerm",
            fields=[
                (
                    "ko_id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="KO ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "ec_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="EC编号"
                    ),
                ),
                ("full_name", models.CharField(max_length=300, verbose_name="全称")),
                (
                    "is_enzyme",
                    models.BooleanField(default=False, verbose_name="是否为酶"),
                ),
            ],
            options={
                "verbose_name": "KO术语",
                "verbose_name_plural": "KO术语",
                "db_table": "ko_term",
                "indexes": [
                    models.Index(
                        fields=["ec_number"], name="ko_term_ec_numb_f4dd14_idx"
                    ),
                    models.Index(
                        fields=["is_enzyme"], name="ko_term_is_enzy_8afe3f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MetabolicPathway",
            fields=[
                (
                    "pathway_id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="通路ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="通路名称")),
                (
                    "full_name",
                    models.CharField(max_length=300, verbose_name="通路全称"),
                ),
                ("ko_id", models.CharField(max_length=10, verbose_name="关联KO ID")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="CottonOGD.metabolicpathway",
                        verbose_name="父级通路",
                    ),
                ),
            ],
            options={
                "verbose_name": "代谢通路",
                "verbose_name_plural": "代谢通路",
                "db_table": "metabolic_pathway",
            },
        ),
        migrations.CreateModel(
            name="PathwayEnzyme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "enzyme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathways",
                        to="CottonOGD.koterm",
                        verbose_name="酶",
                    ),
                ),
                (
                    "pathway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enzymes",
                        to="CottonOGD.metabolicpathway",
                        verbose_name="代谢通路",
                    ),
                ),
            ],
            options={
                "verbose_name": "通路-酶关联",
                "verbose_name_plural": "通路-酶关联",
                "db_table": "pathway_enzyme",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="分类ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="CottonOGD.category",
                        verbose_name="父级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "db_table": "category",
                "indexes": [
                    models.Index(fields=["parent"], name="category_parent__869b08_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="metabolicpathway",
            index=models.Index(
                fields=["parent"], name="metabolic_p_parent__2bcdcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metabolicpathway",
            index=models.Index(fields=["ko_id"], name="metabolic_p_ko_id_23ae2e_idx"),
        ),
        migrations.AddIndex(
            model_name="pathwayenzyme",
            index=models.Index(
                fields=["pathway"], name="pathway_enz_pathway_55bdb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pathwayenzyme",
            index=models.Index(
                fields=["enzyme"], name="pathway_enz_enzyme__46feb3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pathwayenzyme",
            unique_together={("pathway", "enzyme")},
        ),
    ]
