# Generated by Django 5.2.3 on 2026-05-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CottonOGD", "0037_ecnumber_koterm_metabolicpathway_pathwayenzyme_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="metabolicpathway",
            name="metabolic_p_parent__2bcdcd_idx",
        ),
        migrations.RemoveField(
            model_name="metabolicpathway",
            name="parent",
        ),
        migrations.AddField(
            model_name="metabolicpathway",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pathways",
                to="CottonOGD.category",
                verbose_name="所属分类",
            ),
        ),
        migrations.AddIndex(
            model_name="metabolicpathway",
            index=models.Index(
                fields=["category"], name="metabolic_p_categor_ce6ad6_idx"
            ),
        ),
    ]
