# Generated by Django 5.2.3 on 2026-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "CottonOGD",
            "0038_remove_metabolicpathway_metabolic_p_parent__2bcdcd_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=500, verbose_name="分类名称"),
        ),
        migrations.AlterField(
            model_name="ecnumber",
            name="name",
            field=models.CharField(max_length=500, verbose_name="EC名称"),
        ),
        migrations.AlterField(
            model_name="koterm",
            name="name",
            field=models.CharField(max_length=500, verbose_name="名称"),
        ),
    ]
