# Generated by Django 5.2.3 on 2025-11-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Species", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="species",
            options={"verbose_name": "物种", "verbose_name_plural": "物种"},
        ),
        migrations.AlterField(
            model_name="species",
            name="Accession",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="登录号"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="Article",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="文章"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="Assembling_institution",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="组装机构"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="Busco",
            field=models.FloatField(blank=True, null=True, verbose_name="BUSCO值"),
        ),
        migrations.AlterField(
            model_name="species",
            name="Category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="类别"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="Cotton_Species",
            field=models.CharField(max_length=255, verbose_name="棉花物种"),
        ),
        migrations.AlterField(
            model_name="species",
            name="Genome_size",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="基因组大小"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="Genome_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="基因组类型"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="LAI_value",
            field=models.FloatField(blank=True, null=True, verbose_name="LAI值"),
        ),
        migrations.AlterField(
            model_name="species",
            name="Ploidy",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="倍性"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="Website",
            field=models.TextField(blank=True, null=True, verbose_name="网站"),
        ),
        migrations.AlterField(
            model_name="species",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="species",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="名称"
            ),
        ),
        migrations.AlterModelTable(
            name="species",
            table="species",
        ),
        migrations.DeleteModel(
            name="Genome",
        ),
    ]
