# Generated by Django 5.2.3 on 2025-11-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Species", "0004_alter_species_busco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="LAI_value",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="LAI值"
            ),
        ),
    ]
