from tkinter import N
from django.db import models
#from Browse.models import Species
'''
class Orthogroups(models.Model):
    col_0 = models.CharField(max_length=255)
    col_1 = models.TextField(blank=True, null=True)
    col_2 = models.TextField(blank=True, null=True)
    col_3 = models.TextField(blank=True, null=True)
    col_4 = models.TextField(blank=True, null=True)
    col_5 = models.TextField(blank=True, null=True)
    col_6 = models.TextField(blank=True, null=True)
    col_7 = models.TextField(blank=True, null=True)
    col_8 = models.TextField(blank=True, null=True)
    col_9 = models.TextField(blank=True, null=True)
    col_10 = models.TextField(blank=True, null=True)
    col_11 = models.TextField(blank=True, null=True)
    col_12 = models.TextField(blank=True, null=True)
    col_13 = models.TextField(blank=True, null=True)
    col_14 = models.TextField(blank=True, null=True)
    col_15 = models.TextField(blank=True, null=True)
    col_16 = models.TextField(blank=True, null=True)
    col_17 = models.TextField(blank=True, null=True)
    col_18 = models.TextField(blank=True, null=True)
    col_19 = models.TextField(blank=True, null=True)
    col_20 = models.TextField(blank=True, null=True)
    col_21 = models.TextField(blank=True, null=True)
    col_22 = models.TextField(blank=True, null=True)
    col_23 = models.TextField(blank=True, null=True)
    col_24 = models.TextField(blank=True, null=True)
    col_25 = models.TextField(blank=True, null=True)
    col_26 = models.TextField(blank=True, null=True)
    col_27 = models.TextField(blank=True, null=True)
    col_28 = models.TextField(blank=True, null=True)
    col_29 = models.TextField(blank=True, null=True)
    col_30 = models.TextField(blank=True, null=True)
    col_31 = models.TextField(blank=True, null=True)
    col_32 = models.TextField(blank=True, null=True)
    col_33 = models.TextField(blank=True, null=True)
    col_34 = models.TextField(blank=True, null=True)
    col_35 = models.TextField(blank=True, null=True)
    col_36 = models.TextField(blank=True, null=True)
    col_37 = models.TextField(blank=True, null=True)
    col_38 = models.TextField(blank=True, null=True)
    col_39 = models.TextField(blank=True, null=True)
    col_40 = models.TextField(blank=True, null=True)
    col_41 = models.TextField(blank=True, null=True)
    col_42 = models.TextField(blank=True, null=True)
    col_43 = models.TextField(blank=True, null=True)
    col_44 = models.TextField(blank=True, null=True)
    col_45 = models.TextField(blank=True, null=True)
    col_46 = models.TextField(blank=True, null=True)
    col_47 = models.TextField(blank=True, null=True)
    col_48 = models.TextField(blank=True, null=True)
    col_49 = models.TextField(blank=True, null=True)
    col_50 = models.TextField(blank=True, null=True)
    col_51 = models.TextField(blank=True, null=True)
    col_52 = models.TextField(blank=True, null=True)
    col_53 = models.TextField(blank=True, null=True)
    col_54 = models.TextField(blank=True, null=True)
    col_55 = models.TextField(blank=True, null=True)
    col_56 = models.TextField(blank=True, null=True)
    col_57 = models.TextField(blank=True, null=True)
    col_58 = models.TextField(blank=True, null=True)
    col_59 = models.TextField(blank=True, null=True)
    col_60 = models.TextField(blank=True, null=True)
    col_61 = models.TextField(blank=True, null=True)
    col_62 = models.TextField(blank=True, null=True)
    col_63 = models.TextField(blank=True, null=True)
    col_64 = models.TextField(blank=True, null=True)
    col_65 = models.TextField(blank=True, null=True)
    col_66 = models.TextField(blank=True, null=True)
    col_67 = models.TextField(blank=True, null=True)
    col_68 = models.TextField(blank=True, null=True)
    col_69 = models.TextField(blank=True, null=True)
    col_70 = models.TextField(blank=True, null=True)
    col_71 = models.TextField(blank=True, null=True)
    col_72 = models.TextField(blank=True, null=True)
    col_73 = models.TextField(blank=True, null=True)
    col_74 = models.TextField(blank=True, null=True)
    col_75 = models.TextField(blank=True, null=True)
    col_76 = models.TextField(blank=True, null=True)
    col_77 = models.TextField(blank=True, null=True)
    col_78 = models.TextField(blank=True, null=True)
    col_79 = models.TextField(blank=True, null=True)
    col_80 = models.TextField(blank=True, null=True)
    col_81 = models.TextField(blank=True, null=True)
    col_82 = models.TextField(blank=True, null=True)
    col_83 = models.TextField(blank=True, null=True)
    col_84 = models.TextField(blank=True, null=True)
    col_85 = models.TextField(blank=True, null=True)
    col_86 = models.TextField(blank=True, null=True)
    col_87 = models.TextField(blank=True, null=True)
    col_88 = models.TextField(blank=True, null=True)
    col_89 = models.TextField(blank=True, null=True)
    col_90 = models.TextField(blank=True, null=True)
    col_91 = models.TextField(blank=True, null=True)
    col_92 = models.TextField(blank=True, null=True)
    col_93 = models.TextField(blank=True, null=True)
    col_94 = models.TextField(blank=True, null=True)
    col_95 = models.TextField(blank=True, null=True)
    col_96 = models.TextField(blank=True, null=True)
    col_97 = models.TextField(blank=True, null=True)
    col_98 = models.TextField(blank=True, null=True)
    col_99 = models.TextField(blank=True, null=True)
    col_100 = models.TextField(blank=True, null=True)
    col_101 = models.TextField(blank=True, null=True)
    col_102 = models.TextField(blank=True, null=True)
    col_103 = models.TextField(blank=True, null=True)
    col_104 = models.TextField(blank=True, null=True)
    col_105 = models.TextField(blank=True, null=True)
    col_106 = models.TextField(blank=True, null=True)
    col_107 = models.TextField(blank=True, null=True)
    col_108 = models.TextField(blank=True, null=True)
    col_109 = models.TextField(blank=True, null=True)
    col_110 = models.TextField(blank=True, null=True)
    col_111 = models.TextField(blank=True, null=True)
    col_112 = models.TextField(blank=True, null=True)
    col_113 = models.TextField(blank=True, null=True)
    col_114 = models.TextField(blank=True, null=True)
    col_115 = models.TextField(blank=True, null=True)
    col_116 = models.TextField(blank=True, null=True)
    col_117 = models.TextField(blank=True, null=True)
    col_118 = models.TextField(blank=True, null=True)
    col_119 = models.TextField(blank=True, null=True)
    col_120 = models.TextField(blank=True, null=True)
    col_121 = models.TextField(blank=True, null=True)
    col_122 = models.TextField(blank=True, null=True)
    col_123 = models.TextField(blank=True, null=True)
    col_124 = models.TextField(blank=True, null=True)
    col_125 = models.TextField(blank=True, null=True)
    col_126 = models.TextField(blank=True, null=True)
    col_127 = models.TextField(blank=True, null=True)
    col_128 = models.TextField(blank=True, null=True)
    col_129 = models.TextField(blank=True, null=True)
    col_130 = models.TextField(blank=True, null=True)
    col_131 = models.TextField(blank=True, null=True)
    col_132 = models.TextField(blank=True, null=True)
    col_133 = models.TextField(blank=True, null=True)
    col_134 = models.TextField(blank=True, null=True)
    col_135 = models.TextField(blank=True, null=True)
    col_136 = models.TextField(blank=True, null=True)
    col_137 = models.TextField(blank=True, null=True)
    col_138 = models.TextField(blank=True, null=True)
    col_139 = models.TextField(blank=True, null=True)
    col_140 = models.TextField(blank=True, null=True)
    col_141 = models.TextField(blank=True, null=True)
    col_142 = models.TextField(blank=True, null=True)
    col_143 = models.TextField(blank=True, null=True)
    col_144 = models.TextField(blank=True, null=True)
    col_145 = models.TextField(blank=True, null=True)
'''
class gene_info(models.Model):
    id = models.BigAutoField(primary_key=True)
    IDs = models.TextField(blank=True, null=True)
    seqid = models.CharField(max_length=100)
    source = models.CharField(max_length=100)
    species = models.CharField(max_length=100, blank=True, null=True)
    type = models.CharField(max_length=100)
    start = models.IntegerField()
    end = models.IntegerField()
    strand = models.CharField(max_length=10)
    attributes = models.TextField(blank=True, null=True)
    class Meta:
        db_table = 'gene_info'
    def __str__(self):
        return self.IDs

class gene_annotation(models.Model):
    id = models.BigAutoField(primary_key=True)
    Gene_ID = models.CharField(max_length=100, blank=True, null=True)
    GO_annotation = models.TextField(blank=True, null=True)
    KEGG_annotation = models.TextField(blank=True, null=True)
    KOG_class = models.TextField(blank=True, null=True)
    KOG_class_annotation = models.TextField(blank=True, null=True)
    Pfam_annotation = models.TextField(blank=True, null=True)
    Swissprot_annotation = models.TextField(blank=True, null=True)
    TrEMBL_annotation = models.TextField(blank=True, null=True)
    nr_annotation = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.Gene_ID

class Genome_Assembly(models.Model):
    #name = models.ForeignKey(Species, on_delete=models.CASCADE,related_name='species')
    name = models.CharField(max_length=100, blank=True, null=True)
    fasta_file = models.FileField(upload_to='data/genomes/')   # 存原始文件
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.name)
    
    # 不存序列，只存坐标，需要时按坐标用 pyfaidx 提取

class gene_seq(models.Model):
    gene_id = models.CharField(max_length=100, blank=True, null=True)
    mrna_id = models.CharField(max_length=100, blank=True, null=True)
    mrna_seq = models.TextField(blank=True, null=True)
    cds_seq = models.TextField(blank=True, null=True)
    upstream_seq = models.TextField(blank=True, null=True)
    downstream_seq = models.TextField(blank=True, null=True)
    protein_seq = models.TextField(blank=True, null=True)
    def __str__(self):
        return str(self.gene_id)

class genome_seq(models.Model):
    gene_id = models.CharField(max_length=100, blank=True, null=True)
    seq = models.TextField(blank=True, null=True)
    def __str__(self):
        return str(self.gene_id)


