# Generated by Django 5.2.7 on 2025-11-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255, verbose_name='批次名称')),
                ('total_records', models.IntegerField(verbose_name='总记录数')),
                ('success_count', models.IntegerField(verbose_name='成功插入数')),
                ('error_count', models.IntegerField(verbose_name='失败数')),
                ('submitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='提交者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='错误日志')),
            ],
            options={
                'verbose_name': '批次提交记录',
                'verbose_name_plural': '批次提交记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmittedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=255, verbose_name='数据名称')),
                ('data_type', models.CharField(choices=[('gene', '基因序列'), ('annotation', '功能注释'), ('expression', '表达数据'), ('variation', '变异数据'), ('other', '其他数据')], max_length=50, verbose_name='数据类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='数据描述')),
                ('gene_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联基因ID')),
                ('species_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='物种名称')),
                ('data_value', models.TextField(blank=True, null=True, verbose_name='数据值')),
                ('submitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='提交者')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='参考文献')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '提交数据',
                'verbose_name_plural': '提交数据',
                'ordering': ['-created_at'],
            },
        ),
    ]
