from django.shortcuts import render

# Create your views here.
def genome(request):
    context = {
        'genome_list': [
           'A1a',
            'A1',
            'A2',
            'B1',
            'C1',
            'D1-35',
            'D1-5',
            'D2-1',
            'D2-2',
            'D3d-27',
            'D3d-8',
            'D3-k',
            'D4',
            'D5',
            'D5-3',
            'D5-4',
            'D5-8',
            'D6',
            'D7',
            'D8',
            'D9',
            'D10',
            'D11',
            'E1',
            'F1',
            'G1',
            'G2',
            'AD1',
            'AD2',
            'AD3',
            'AD4',
            'AD5',
            'AD6',
            'AD7',
           ' A2',
            'B1',
            'C1',
            'D1-35',
            'D1-5',
            'D2-1',
            'D2-2',
            'D3d-27',
            'D3d-8',
            'D3-k',
            'D4',
            'D5',
            'D5-3',
            'D5-4',
            'D5-8',
            'D6',
            'D7',
            'D8',
            'D9',
            'D10',
            'D11',
            'E1',
            'F1',
            'G1',
            'G2',
            'AD1',
            'AD2',
            'AD3',
            'AD4',
            'AD5',
            'AD6',
            'AD7',
        ]
    }
    return render(request, 'Genome/index.html',context)
