# Generated by Django 5.2.3 on 2025-11-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TF",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
                ("genome", models.CharField(max_length=100)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("strand", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
