# Generated by Django 5.2.3 on 2025-12-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TF', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tf',
            old_name='genome',
            new_name='TF_class',
        ),
        migrations.RenameField(
            model_name='tf',
            old_name='name',
            new_name='TF_gene',
        ),
        migrations.RenameField(
            model_name='tf',
            old_name='species',
            new_name='TF_genome',
        ),
        migrations.RenameField(
            model_name='tf',
            old_name='type',
            new_name='TF_name',
        ),
        migrations.RemoveField(
            model_name='tf',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tf',
            name='end',
        ),
        migrations.RemoveField(
            model_name='tf',
            name='start',
        ),
        migrations.RemoveField(
            model_name='tf',
            name='strand',
        ),
    ]
