# Generated by Django 5.2.3 on 2025-12-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('Cotton_Species', models.CharField(blank=True, max_length=255, null=True, verbose_name='棉花物种')),
                ('Genome_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='基因组类型')),
                ('Category', models.CharField(blank=True, max_length=100, null=True, verbose_name='类别')),
                ('Accession', models.CharField(blank=True, max_length=100, null=True, verbose_name='登录号')),
                ('Ploidy', models.CharField(blank=True, max_length=50, null=True, verbose_name='倍性')),
                ('Assembling_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='组装机构')),
                ('Website', models.TextField(blank=True, null=True, verbose_name='网站')),
                ('Article', models.CharField(blank=True, max_length=255, null=True, verbose_name='文章')),
                ('LAI_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='LAI值')),
                ('Busco', models.CharField(blank=True, max_length=100, null=True, verbose_name='BUSCO值')),
                ('Genome_size', models.BigIntegerField(blank=True, null=True, verbose_name='基因组大小')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TF',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('TF_gene', models.CharField(db_column='TF_gene', max_length=100)),
                ('TF_genome', models.CharField(db_column='TF_genome', max_length=100)),
                ('TF_class', models.CharField(db_column='TF_class', max_length=100)),
                ('TF_name', models.CharField(db_column='TF_name', max_length=100)),
            ],
            options={
                'db_table': 'tf_tf',
                'managed': False,
            },
        ),
    ]
