# Generated by Django 5.2.3 on 2025-12-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tf',
            options={},
        ),
    ]
