# Generated by Django 5.2.3 on 2025-12-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0002_alter_species_options_alter_tf_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tf',
            name='TF_name',
            field=models.CharField(db_column='subfamily', max_length=100),
        ),
        migrations.AlterField(
            model_name='tf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
