# Generated by Django 5.2.3 on 2025-12-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0003_alter_tf_tf_name_alter_tf_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='tf',
            name='TF_name',
            field=models.CharField(db_column='TF_name', max_length=100),
        ),
    ]
