# Generated by Django 5.2.3 on 2025-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutGhirsutumTm1WhuStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_query', models.CharField(db_column='_query', max_length=20)),
                ('seed_ortholog', models.CharField(max_length=40)),
                ('evalue', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.SmallIntegerField()),
                ('eggnog_ogs', models.CharField(max_length=190)),
                ('max_annot_lvl', models.CharField(max_length=40)),
                ('cog_category', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('preferred_name', models.CharField(max_length=10)),
                ('gos', models.TextField()),
                ('ec', models.CharField(max_length=80)),
                ('kegg_ko', models.CharField(max_length=100)),
                ('kegg_pathway', models.TextField()),
                ('kegg_module', models.CharField(max_length=80)),
                ('kegg_reaction', models.TextField()),
                ('kegg_rclass', models.CharField(max_length=190)),
                ('brite', models.CharField(max_length=100)),
                ('kegg_tc', models.CharField(max_length=60)),
                ('cazy', models.CharField(max_length=20)),
                ('bigg_reaction', models.CharField(max_length=30)),
                ('pfams', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'out_ghirsutum_tm_1_whu_standard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GOEnrichmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_genes', models.TextField()),
                ('background_genes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('results_json', models.JSONField()),
            ],
        ),
    ]
