# Generated by Django 5.2.3 on 2025-06-18 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orthogroup',
            fields=[
                ('orthogroup_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=50)),
                ('genome', models.CharField(max_length=50)),
                ('orthogroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.orthogroup')),
            ],
            options={
                'unique_together': {('gene_id', 'genome')},
            },
        ),
    ]
